### ISSUE TITLE
Can stream handle multiple output paths in webpack?

### ISSUE THREAD

**Issue by clodal** [shama/webpack-stream#133]
Hi, can webpack-stream handle paths in the webpack entry point object key?

It works in webpack itself [webpack multiple output paths issue](https://github.com/webpack/webpack/issues/1189) as per @sashless's answer there.

But when i try to run that code with the webpack-stream wrapper, it seems to throw an error.

Is this feature supported?

1. Setup gulpfile with webpack-stream wrapping webpack
```
// gulpfile.js
var webpack = require('webpack-stream');

gulp.task('webpack', function () {
    return webpack({
            entry: {
                'card/main': './assets/coffee/app/card/main.coffee', // outputs /js/app/card/main.js
                'card/cart':  './assets/coffee/app/card/cart.coffee', // outputs /js/app/card/cart.js
            },
            output: {
                path: './assets/js/app',
                filename: '[name].js'
            }
        })
        .pipe(gulp.dest('./dist/bundle'));
});
```

2. Run the gulp command in command line
```
$ gulp webpack
```

3. Returns error
```
// unix

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid argument
  at pathToArray (/Users/Sites/app/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
  at MemoryFileSystem.mkdirpSync (/Users/Sites/app/node_modules/memory-fs/lib/MemoryFileSystem.js:139:13)
  at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/Sites/app/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
```

**Comment by clodal** [comment]
Found the answer here: https://github.com/shama/webpack-stream/issues/128
