### ISSUE TITLE
Stopped working in 4.0

### ISSUE THREAD

**Issue by NN---** [shama/webpack-stream#165]
I use gulp with webpack-stream and get this in 4.0.
With 3.2.0 everything works perfect.

```
2>  [23:16:41] 'build.chrome.webpack' errored after 423 ms
2>  [23:16:41] WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
2>   - configuration.resolve.extensions[0] should not be empty.
2>      at webpack (test\node_modules\webpack\lib\webpack.js:19:9)
2>      at Stream.<anonymous> (test\node_modules\webpack-stream\index.js:132:20)
2>      at _end (test\node_modules\through\index.js:65:9)
2>      at Stream.stream.end (test\node_modules\through\index.js:74:5)
2>      at module.exports (test\node_modules\webpack-stream\index.js:206:12)
2>      at runWebpack (test\gulpfile.js:197:9)
2>      at Gulp.<anonymous> (test\gulpfile.js:226:9)
2>      at module.exports (test\node_modules\orchestrator\lib\runTask.js:34:7)
2>      at Gulp.Orchestrator._runTask (test\node_modules\orchestrator\index.js:273:3)
2>      at Gulp.Orchestrator._runStep (test\node_modules\orchestrator\index.js:214:10)
2>      at Gulp.Orchestrator.start (test\node_modules\orchestrator\index.js:134:8)
2>      at test\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:54:20
2>      at _combinedTickCallback (internal/process/next_tick.js:131:7)
2>      at process._tickCallback (internal/process/next_tick.js:180:9)
2>      at Function.Module.runMain (module.js:667:11)
2>      at startup (bootstrap_node.js:187:16)
```

My webpack entry is:

```

module.exports = {
	entry: {
		tests: ["./tests/testShims.ts"].concat(glob.sync("./tests/**/*.ts"))
	},
```

It does work with simple array, but I don't want to write all files manually and it worked in previous version.

**Comment by shama** [comment]
`- configuration.resolve.extensions[0] should not be empty.`

**Comment by NN---** [comment]
@shama Sorry, I don’t understand. How should I fix my code?

**Comment by NN---** [comment]
Ok, I found the problem.
