### ISSUE TITLE
Add a `watch` option. E.g. webpack({watch: true})

### ISSUE THREAD

**Issue by koistya** [shama/webpack-stream#18]
With this flag set to true, the plugin would run bundler in a watch mode - `bundler.watch(..)`, instead of `bundler.run(..)`.

``` javascript
var gulp = require('gulp');
var webpack = require('gulp-webpack');

gulp.task('bundle', function () {
  return gulp.src('src/app.jsx')
    .pipe(webpack({watch: true}))
    .pipe(gulp.dest('./build'));
});
```

**Comment by frank-weindel** [comment]
I'm getting the repeated console output that @tinchoz49 mentioned. The watch seems to be working though, but it causes webpack's actual output to quickly scroll off screen.

**Comment by moimikey** [comment]
i did mine this way:

```
var extend = require('lodash').extend;

gulp.task('build', ['lint'], function() {
  return gulp.src(settings.paths.source.lib)
    .pipe(plugin.plumber())
    .pipe(plugin.webpack(webpack))
    .pipe(gulp.dest(settings.paths.destination.bundle));
});

gulp.task('watch', ['lint'], function() {
  return gulp.src(settings.paths.source.lib)
  .pipe(plugin.plumber())
  .pipe(plugin.webpack(extend({}, webpack, { watch: true })))
  .pipe(gulp.dest(settings.paths.destination.bundle));
});
```

**Comment by MadLittleMods** [comment]
`.pipe(webpack({watch: true}))` works but it seems to stop my other `gulp.watch` tasks. My watch tasks work completely fine when I don't run the `gulp-webpack` task.

**Comment by mrmuh** [comment]
hi! I am also searching for an working example how to use the watch function together with webpack-stream. At the moment I have the problem that the first pass generates the expected output, further changes are detected but the updates are not written into the file!

**Comment by ianbytchek** [comment]
:+1:

**Comment by wormyy** [comment]
+1

**Comment by yu521088** [comment]
I tried this way: 
```
var webpack = require('webpack');
var path = require('path');
// var commonsPlugin = new webpack.optimize.CommonsChunkPlugin('common.js');

module.exports = {
  entry: {
    index: ['webpack-dev-server/client?http://localhost:8080',
    'webpack/hot/dev-server',
    './src/js/index.js']
    // index: './src/js/index.js'
  },
  output: {
    path: path.resolve(__dirname, 'build/js/'),
    filename: '[name].js'
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.less']
  },
  module: {
    loaders: [{
      test: /\.js$/,
      include: [path.join(__dirname, 'src')],
      loaders: ['react-hot', 'babel-loader?presets[]=react,presets[]=es2015']
    },
    { test: /\.css$/, loader: "style!css" },
    { test: /\.less$/, loader: "style!css!less" }]
  },
  watch: true,
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ]
  // plugins: [commonsPlugin]
};
```
and add gulp task:
```
gulp.task('webpack-dev-server', function(callback) {
	// modify some webpack config options
	var myConfig = Object.create(webpackConfig);
	myConfig.devtool = 'eval';
	myConfig.debug = true;

	// Start a webpack-dev-server
	new WebpackDevServer(webpack(myConfig), {
		// publicPath: '/' + myConfig.output.publicPath,
    contentBase: './build/',
		stats: {
			colors: true
		},
    hot: true
	}).listen(8080, 'localhost', function(err) {
		if(err) throw new gutil.PluginError('webpack-dev-server', err);
		gutil.log('[webpack-dev-server]', 'http://localhost:8080/webpack-dev-server/index.html');
	});
});
```
It doesn't work, it only works for gulp watch, which is not what i want and it's quit slow:

```
gulp.task('build-dev', ['html-minify', 'webpack:build-dev'], function() {
	 gulp.watch(['src/**/*'], ['webpack:build-dev']);
});
```

**Comment by gregorybolkenstijn** [comment]
I also can't seem to find a way to get the watch working with Gulp. Only the first run works, after that nothing happens and it blocks my other tasks.

**Comment by MarkLeMerise** [comment]
I am experiencing the same issue as @gregorybolkenstijn. I can pass in `watch: true` and I get a console message saying that webpack is watching but it blocks the rest of my pipeline. I tried using `gulp-plumber` per @moimikey's suggestion but saw the same results.

**Comment by ElsewhereGames** [comment]
@MarkLeMerise Are you `return`-ing the gulp pipeline? Instead of:

```
gulp.task(
  'deploy-typescript',
  function() {
    return gulp.src('app.js')
      .pipe(webpackStream(webpackConfiguration))
      .pipe(gulp.dest('bundle.js'));
  }
);
```

Try:

```
gulp.task(
  'deploy-typescript',
  function() {
    gulp.src('app.js')
      .pipe(webpackStream(webpackConfiguration))
      .pipe(gulp.dest('bundle.js'));
  }
);
```

**Comment by ElsewhereGames** [comment]
I just noticed that what I suggest will only work when you intend to run an actual server, since that task never returns. If you just want to a one-off build, the task will block indefinitely.

**Comment by dlebedynskyi** [comment]
having simmilar issue. with watch:true webpack crushed on first error and terminates whole task. `gulp-webpack` could still continue working

**Comment by samanime** [comment]
I did some testing.

With just `{watch:true}` passed to the call, it built and watched.

With this config passed:
```
{
    watch: true,
    context: __dirname + "/app/www/scripts",
    entry: "./app.js",
    output: {
        path: __dirname + "/dist/www/scripts",
        filename: "app.js"
    }
}
```
it built but did NOT watch.

With this config:
```
watch: true,
    entry: __dirname + "/app/www/scripts/app.js",
    output: {
        path: __dirname + "/dist/www/scripts",
        filename: "app.js"
    },
```
it built and watched. Notice the lack of `context` and the changed `entry` value.

It seems like the watcher gets some wires crossed with context.

On a side note, the "watch" portion of the documentation (http://webpack.github.io/docs/configuration.html#watch) gets removed with JavaScript for some reason. If you disable JavaScript and load the page, it's there. No clue what that's about.

**Comment by MarkLeMerise** [comment]
@ElsewhereGames Yes, I was `return`ing the pipeline.

**Comment by abjrcode** [comment]
Hey gents,
I use the watch option and it was working fine, until I started passing an array of configurations to webpack and then it doesn't work anymore. Is that supported for an array of configurations ?

I have something like this:

    gulp.task('webpack', ['clean'], function() {
    
      return webpack([gonfigA, gonfigB, gonfigC], function(err, stats) {
        
          if (err) throw new gutil.PluginError("webpack", err);
          
          gutil.log("[webpack]", stats.toString({
            chunks: false,
            colors: true
          }));
          
          gutil.log("[webpack]", "Gonna sit around and watch for file changes. CTRL^C to kill me");
      });
      
    });


**NOTE:** I am not using the webpack dev server and don't have the intention to.

**Comment by wphampton** [comment]
Perhaps this will help someone else.  I thought I'd share since the above conversation helped me out along my way.  https://github.com/shama/webpack-stream/issues/105#issuecomment-219740738

**Comment by zaqqaz** [comment]
`
if (errors.length) {
        var errorMessage = errors.reduce(function (resultMessage, nextError) {
          resultMessage += nextError.toString();
          return resultMessage;
        }, '');

        self.emit('error', new gutil.PluginError('webpack-stream', errorMessage));
      }
`

If use ts-loader and watch mode, after first error in code,
 code above emit error, after that,
 **dest pipe (all below)  no longer work**, while webpack is watching for changes.

`.pipe(webpackStream(webpackOptions, null, webpackChangeHandler))
 .pipe(gulpDest)`

**Comment by jmurzy** [comment]
For those of you who are still having issues with Weback `watch`, I created a PR that should address this in a more gulp friendly way. See #109. Let me know how this works for you guys.

**Comment by alberto2000** [comment]
Sorry, newbie here - so am I right, there's currently no way to use webpack in cached & therefore fast watch mode from within gulp? My ideal workflow involves using webpack just for transpiling and module loading and then gulp for building and bundling etc. Hope that PR gets accepted and solved the issue!

**Comment by mikemcguire** [comment]
@alberto2000  You can, just use separate tasks. If you have a watch-styles task and a watch-js task, you then make them a dependency on a watch task that will run both of them separately.

**Comment by AlennGK** [comment]
If you cancel --watch function how long does it take to cancel. Mine is like 60s or more.

**Comment by cowwoc** [comment]
@shama While I appreciate @jmurzy trying to help by contributing #109 it doesn't really solve the problem. In my view it only makes matters worse by leading users to the wrong solution.

If you try running webpack `watch: true` without this plugin versus using this plugin with the approach in #109 you will notice a 10x performance decrease. On my end, webpack `watch: true` takes 100ms and #109 takes 1-2 seconds.

It doesn't seem to be possible to pass `webpack: true` using this plugin because Webpack 5 now warns:

```
(node:20156) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
    at webpack (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\webpack\lib\webpack.js:145:5)
    at f (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\webpack\lib\index.js:35:15)
    at Stream.<anonymous> (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\webpack-stream\index.js:150:38)
    at _end (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:433:28)
    at DestroyableTransform.emit (node:events:339:22)
    at DestroyableTransform.EventEmitter.emit (node:domain:548:15)
    at endReadableNT (C:\Users\Gili\Documents\holdmyspot\shopping\client\browser\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
```

and does not recompile on file change. Again, running the `watch` configuration without this plugin works just fine. Can we add a `callback` argument to `webpack-stream` to pass to the underlying `webpack` constructor?

**Comment by julianmesa-gitkraken** [comment]
@shama @MarkLeMerise @cowwoc Finally I have found the problem about watch. You have to call to the callback to close the task and contnue the pipeline Can you update the readme?
Example:
```
const gulp = require('gulp');
const webpack = require('webpack-stream');
gulp.task('default', function(cb) {
  gulp.src('src/entry.js')
    .pipe(webpack({
    watch: true,
    ............
    }))
    .pipe(gulp.dest('dist/'));
  cb();
});
```
