### ISSUE TITLE
WebpackOptionsValidationError

### ISSUE THREAD

**Issue by NasKadir123** [shama/webpack-stream#218]
Hi!
I have some problem with webpack-stream version 5.2.1.
I'm using it with gulp and have this error:
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/webpack/lib/webpack.js:31:9)
    at Stream.<anonymous> (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/webpack-stream/index.js:154:38)
    at _end (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:203:15)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at drain (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/through/index.js:45:5)
    at Stream.end (/Applications/MAMP/htdocs/wordpress/wp-content/themes/modest_portfolio_theme/node_modules/through/index.js:15:35)

I'm using babel-loader for ES6, vinyl-named and yargs. Error come in this task with scripts:

```
const PRODUCTION = yargs.argv.prod;

const paths = {
  scripts: {
    src: [
      "src/assets/js/bundle.js",
      "src/assets/js/admin.js",
      "src/assets/js/customize-preview.js"
    ],
    dest: "dist/assets/js"
  }
};

export const scripts = () => {
  return gulp
    .src(paths.scripts.src)
    .pipe(named())
    .pipe(
      webpack({
        module: {
          loaders: [
            {
              test: /\.js$/,
              use: {
                loader: "babel-loader",
                options: {
                  presets: ["babel-preset-env"]
                }
              }
            }
          ]
        },
        output: {
          filename: "[name].js"
        },
        externals: {
          jquery: "jQuery"
        },
        devtool: !PRODUCTION ? "inline-source-map" : false
      })
    )
    .pipe(gulpif(PRODUCTION, uglify()))
    .pipe(gulp.dest(paths.scripts.dest));
};

```

This code has worked in webpack-stream version 4.0.3.
What should I do? Can you help me, please?

**Comment by shama** [comment]
`webpack-stream@5` upgraded to `webpack@4` where they've made some config changes: https://webpack.js.org/migrate/4/#moduleloaders You might just need to rename `loaders` to `rules`.

If you can't upgrade to `webpack@4` yet though, you can install whatever version of webpack your build is currently compatible with and feed that version of webpack as a compiler: https://github.com/shama/webpack-stream#usage-with-gulp-watch

**Comment by NasKadir123** [comment]
> `webpack-stream@5` upgraded to `webpack@4` where they've made some config changes: https://webpack.js.org/migrate/4/#moduleloaders You might just need to rename `loaders` to `rules`.
> 
> If you can't upgrade to `webpack@4` yet though, you can install whatever version of webpack your build is currently compatible with and feed that version of webpack as a compiler: https://github.com/shama/webpack-stream#usage-with-gulp-watch

Thanks!!!
Sorry for late answer, it gets worked!
