### ISSUE TITLE
Support webpack version 5

### ISSUE THREAD

**Issue by kevinlandsberg** [shama/webpack-stream#224]
I am using webpack@next version, whcih is actually 5.0.0.....i am getting errors like following during my gulp task:

`WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the AP - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry['appbundle'] should be a string.
      -> The string is resolved to a module which is loaded upon startup.
    * configuration.entry['appbundle'] should be an array:
      [non-empty string]
      -> A non-empty array of non-empty strings
    * configuration.entry['appbundle'] should be one of these:
      [non-empty string]
      -> All modules are loaded upon startup. The last one is exported.
    * configuration.entry['appbundle'] should be one of these:
      non-empty string | [non-empty string]
      -> An entry point with name
    at webpack (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\node_modules\webpack-stream\node_modules\webpack\lib\webpack.js:31:9)
    at Stream.<anonymous> (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\node_modules\webpack-stream\index.js:150:38)
    at _end (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\node_modules\through\index.js:74:5)
    at module.exports (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\node_modules\webpack-stream\index.js:225:12)
    at createBundleTask (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\gulpfile.ts:81:9)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (C:\Users\Kevin\Development\InnoEcos\InnoEcos.Applications.Web\node_modules\async-done\index.js:55:18)`

**Comment by phil-w** [comment]
I'm using  wbepack 6 (currently rc.3) and it works fine for me. Perhaps you are using webpack-stream's copy of webpack, which is v4, rather than v5, hence the schema is different?

Type "npm list webpack" and look under webpack-stream for the version webpack  it is using.
If you want to run webpack 5, you need to load that separately as described on the documentation page as:

> "If you would like to use a different version of webpack than the one this plugin uses, pass in an optional 2nd argument:"

**Comment by kevinlandsberg** [comment]
Hey @phil-w ,

thx for the advice. With ES6 Modules i had to use following code snippet to make it run without ts errors:

`import webpack from 'webpack';`
`import webpackStream from 'webpack-stream';`
`import WebpackConfig from './webpack.config';`
`const createBundleTask = () => {`
    `//@ts-ignore`
    `return webpackStream(WebpackConfig, webpack).pipe(`
        `gulp.dest(`./${outputFilesPath}/default/deploy/`)`
    `);`
`};`

**Comment by kevinlandsberg** [comment]
> Hey @phil-w ,
> 
> thx for the advice. With ES6 Modules i had to use following code snippet to make it run without ts errors:
> 
> `import webpack from 'webpack';`
> `import webpackStream from 'webpack-stream';`
> `import WebpackConfig from './webpack.config';`
> `const createBundleTask = () => {`
> `//@ts-ignore`
> `return webpackStream(WebpackConfig, webpack).pipe(`
> `gulp.dest(`./${outputFilesPath}/default/deploy/`)`
> `);`
> `};`

I had to use @ts-ignore to ignore ts errors cause of typeof webpack in second argument of webpack-stream
