### ISSUE TITLE
The example doesn't work in 2.1.0

### ISSUE THREAD

**Issue by veu** [shama/webpack-stream#69]
The [very first example](https://github.com/shama/webpack-stream/blob/master/readme.md#usage) in the documentation fails in 2.1.0 with the following error.

```
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at clone (/.../node_modules/webpack-stream/index.js:170:10)
    at module.exports (/.../node_modules/webpack-stream/index.js:26:13)
    at Gulp.<anonymous> (/.../gulpfile.js:6:11)
    at module.exports (/.../node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/.../node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/.../node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/.../node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:121:20
    at process._tickCallback (node.js:415:13)
```

This is because *options* is passed to Object.keys without checking whether it's an object and it's `undefined` in this case.

**Comment by soulhunter1987** [comment]
Confirm...

**Comment by anselmbradford** [comment]
+1

**Comment by vanderlin** [comment]
+1

**Comment by FQ400** [comment]
+1

**Comment by baybara-pavel** [comment]
+1

**Comment by artparks** [comment]
when will this be in a tagged release?
