### ISSUE TITLE
webpack-stream fails to use babel-loader

### ISSUE THREAD

**Issue by lcxfs1991** [shama/webpack-stream#71]
Have you ever tried this?

I try but it pops up that I may use an appropriate loader to parse the file.

**Comment by superlukas** [comment]
Works fine over here. Do you want to post your config?

**Comment by lcxfs1991** [comment]
I finally works out. It'd better you post an example for reference since a lot of people are new to webpack let along gulp-webpack. My config solution is as follows.

```
webpack: {
     //entry files   页面入口文件配置
    entry: {
        index : ['./src/js/_index/main.js']
    },
    //output files 入口文件输出配置
    output: {
        path: './dev/js/',
	filename: '[name].js'
    },
    module: {
    //loaders 加载器配置
        loaders: [
            {
	        test: /\.js$/,
	        loader: 'babel-loader'
	    }
	 ]
     },
     //other config 其它解决方案配置
    resolve: {
        extensions: ["", ".js", ".jsx", '.es6'],
     }
}
```

**Comment by lcxfs1991** [comment]
But it is wired that I can't parse jsx file correct like js event I use following loader, why?

```
{
    test: /\.jsx$/,
    loader: 'babel-loader!jsx-loader?harmony'
}
```

**Comment by superlukas** [comment]
I'm not sure about JSX since I don't use it. But I think this should work:

```js
module: {
  loaders: [
    {
      test: /\.jsx?$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel'
    }
  ]
}
```

It's taken from their [docs](https://github.com/babel/babel-loader), but my config looks pretty much the same. Are you using React < 0.12? If so, you should probably look into this: https://babeljs.io/docs/advanced/transformers/other/react-compat/

**Comment by rapilabs** [comment]
I've discovered that since webpack-stream introduced it's own cloning in commit fe2be67036dcd197ba1b99c1ec277b81a6a2be03, my configuration which was cloned with Object.create() no longer works (due to the fact that all properties were now in the object's prototype)

**Comment by Nicolab** [comment]
+1 
Doesn't work when the config is copied with `Object.create()`. gulp-webpack work in this case.

**Comment by ianwith** [comment]
any progress?

**Comment by lcxfs1991** [comment]
I am dumping gulp recently and using webpack directly to build my project. Except image sprites, everything works fine.

**Comment by ianwith** [comment]
I am just using Node's built-in util._extend() for cloning my webpack config, instead of Object.create()

**Comment by futurechallenger** [comment]
i met this problem too. I used webpack@2.2.1, configed like this:
```
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'built/client/assets');
var APP_DIR = path.resolve(__dirname, 'client/H5');

var config = {
  entry: APP_DIR + '/index.js',
  output: {
    path: BUILD_DIR,
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          'babel-loader',
        ],
        include: [
          // path.resolve(__dirname, "app")
          APP_DIR
        ],
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader?modules',
          'postcss-loader',
        ]
      }
    ]
  }
};

module.exports = config;

```

in *babel.gulp.js*:

```
// some other import is ...
import gulpWebpack from 'webpack-stream'
import webpack from 'webpack'

const paramConfig = {
  source: 'server/**/*.js',
  clientSource: 'client/H5/index.js',
  serverDest: './built/server',
  clientDest: './built/client',
}

gulp.task('webpack', () => {
  return gulp.src(paramConfig.clientSource)
    .pipe(gulpWebpack({}, webpack))
    .pipe(gulpWebpack(require('./webpack.config.js')))
    .pipe(gulp.dest(paramConfig.clientDest))
})
```

**Comment by wuyuchang** [comment]
I also meet the same problem, how do you solve it? @futurechallenger

**Comment by wuyuchang** [comment]
`webpack.config.prod.js`
``` javascript
const vendor = require('./vendor.json')
const webpack = require('webpack')
const path = require('path')

module.exports = {
  entry: {
    app: path.resolve(__dirname, 'master/jsx/App'),
    // vendor: vendor
  },
  output: {
    filename: 'app.bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  resolve: {
    extensions: ['.js', '.jsx']
  },
  module: {
    rules: [{
      test: /\.js$/,
      use: [ 'babel-loader'],
      exclude: /node_modules/
    }, {
      test: /\.jsx$/,
      use: ['babel-loader'],
      exclude: /node_modules/
    }]
  },
  plugins: [
    // new webpack.optimize.CommonsChunkPlugin({
    //   name: 'vendor',
    //   filename: 'vendor.bundle.js'
    // }),
    // new webpack.optimize.OccurenceOrderPlugin(),
    // new webpack.optimize.UglifyJsPlugin({
    //   compressor: {
    //     warnings: false
    //   }
    // })
  ]
}
```
`gulpfile.js`
``` javascript
gulp.task('build', () => {
  // console.log(webpackConfig)
  return gulp.src('./master/jsx/App.js')
    .pipe(webpackStream(webpackConfig), webpack)
    .pipe(gulp.dest('dist/'))
})
```

I get this issue:
C:\Users\ou_di\www\GAD>gulp build --prod
[15:29:48] Using gulpfile ~\www\GAD\gulpfile.js
[15:29:48] Starting 'build'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./master/jsx/App.js
Module parse failed: C:\Users\ou_di\www\GAD\master\jsx\App.js Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (10:2)
    at Parser.pp$4.raise (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (C:\Users\ou_di\www\GAD\node_modules\webpack-stream\node_modules\acorn\dist\acorn.js:1796:19)

**Comment by davidwesst** [comment]
Is there any update on this issue? I'm hitting the same problem, and my work around is to not use webpack-stream for the time being.

**Comment by wuyuchang** [comment]
@davidwesst  I find the issue, I'm using webpack2 but seems webpack-stream not work with webpack2 well, so I use webpack1 instead of the webpack2, then it's work. unfortunately, I can't not use webpack2 anymore, I hope the author of webpack-stream can resolve this issue as fast.

**Comment by brewaa** [comment]
I just had this same problem.

I could get the babel-loader to work when just using webpack. When i moved to using gulp, the babel-loader doesn't seem to work.

Here's my config:

entry: {
            vendor: ["react", "react-dom"], 
            app: "./wwwroot/dist/tmp/app.js"
        },
        output: {
            path: path.resolve(outputDir + '/js'),
            filename: "[name].js"
        },
        devtool: "source-map",
        module: {
            loaders: [
                {
                    test: /\.jsx?$/,
                    loader: "babel-loader",
                    query:
                    {
                        presets:['react', 'ES2015']
                    }
                }
            ]
        },
        resolve: {
            extensions: ['.js', '.jsx'],
            modules: [
                path.resolve('node_modules')
            ]
        },
        plugins: [
            new webpack.optimize.CommonsChunkPlugin({
                name: 'vendor',
                minChunks: function(module) {
                  return isExternal(module);
                }
            })
        ]
    }

Does anything look wrong with my config?

If you're struggling for time can you point me in the right direction and I can pull and submit a fix if there is an issue with webpack-stream?

**Comment by 112KA** [comment]
I also met same problem.
In my case, I referred to the following link.
[https://github.com/babel/babel-loader/issues/463](https://github.com/babel/babel-loader/issues/463)
It was solved by reading the babel preset module directly in the config file.
